#!/bin/bash

logdatei='/var/ramdisk/openvpn-status.log'
emailadr='root@localhost'

clients=$(awk '/^CLIENT_LIST/ {print $2 " " $3}' $logdatei)
clientips=$(awk '/^CLIENT_LIST/ {print $3}' $logdatei | cut -d '.' -f1-2)

foreign=false
for clientip in $clientips; do
	if [ $clientip != "192.168" ]; then
		foreign=true
	fi
done

if $foreign; then
	[[ -f "/var/ramdisk/openvpnforeign.lock" ]] || mail -s "Fremder VPN-Login" $emailadr <<< $clients
	touch /tmp/ramdisk/openvpnforeign.lock
else
	[[ -f "/var/ramdisk/openvpnforeign.lock" ]] && rm /tmp/ramdisk/openvpnforeign.lock
fi

exit 0
