#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#################################################
# Skript zum Auslesen des VPN-Server-Status     #
# --------------------------------------------- #
# Erstellt von Johannes Paul, 09.04.2014        #
# Bearbeitet am 17.11.2018                      #
# --------------------------------------------- #
# Syntax: vpnstatus [tel]                       #
# Parameter (VPN-Server):                       #
#    tel - Telnet statt Logdatei                #
#################################################

# Import
import sys
import time
import curses
import vpnstatus_parser
from curseslib import initialize_colors

def main(screen):
    initialize_colors()
    
    screen.nodelay(1)
    
    if 'tel' in sys.argv:
        tel = True
    else:
        tel = False
    
    while True:
        # Exit with <q>
        c = screen.getch()
        if c == ord('q'):break
        screen.clear()
        screen.move(0,0)
        screen.addstr("Zum Beenden <q> drücken!\n\n", curses.color_pair(1) | curses.A_BOLD)
        screen.addstr("Serverstatus:\n")

        status, statusline = vpnstatus_parser.get_service_info()
    
        vpnstatus_parser.curses_status(screen, status, statusline)
        screen.addstr("\n")
        if status == 'aktiv':
            clients = vpnstatus_parser.get_status_info(tel)
            vpnstatus_parser.curses_clients(screen, clients)
    
        screen.refresh()
        # Wait a moment
        time.sleep(1)
    curses.endwin()
    
curses.wrapper(main)
